### GET All persons
GET http://localhost:3001/api/persons/

### GET a specific person
GET http://localhost:3001/api/persons/1

### DELETE a specific person
DELETE http://localhost:3001/api/persons/4

### POST a new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Gaston Lagaffe",
  "number": "71-600-500"
}